version: 2
jobs:
  ubuntu-foccal:
    docker:
      - image: buildpack-deps:focal-curl
        environment:
          DEBIAN_FRONTEND: noninteractive
    working_directory: /workspace
    steps:
      - checkout
      - run: apt-get update -qq
      - run: apt install -y --no-install-recommends qt5-default qt5-qmake libqt5sql5-mysql libqt5sql5-psql libqt5sql5-odbc libqt5sql5-sqlite libqt5core5a libqt5qml5 libqt5xml5 qtbase5-dev qtdeclarative5-dev qtbase5-dev-tools gcc g++ make cmake
      - run: apt install -y --no-install-recommends libmysqlclient-dev libpq5 libodbc1 libmongoc-dev libbson-dev
      - run: wget https://github.com/treefrogframework/treefrog-framework/archive/v1.30.0.tar.gz
      - run: tar zxvf v*.*.*.tar.gz
      - run: mv treefrog-framework-*.* treefrog-framework
      - run: cd treefrog-framework && ./configure --prefix=/usr/local
      - run: cd treefrog-framework && make -j4 -C src
      - run: cd treefrog-framework && make install -C src 
      - run: cd treefrog-framework && make -j4 -C tools
      - run: cd treefrog-framework && make install -C tools
      - run: ldconfig
      - run: treefrog -v
      - persist_to_workspace:
          root: /
          paths:
            - workspace/treefrog-framework
            - usr/local
  build_project:
    docker:
      - image: buildpack-deps:focal-curl
        environment:
          DEBIAN_FRONTEND: noninteractive
    working_directory: /workspace/treefrog-framework
    steps:
      - attach_workspace:
          at: /
      - run: apt-get update -qq
      - run: apt install -y --no-install-recommends qt5-default qt5-qmake libqt5sql5-mysql libqt5sql5-psql libqt5sql5-odbc libqt5sql5-sqlite libqt5core5a libqt5qml5 libqt5xml5 qtbase5-dev qtdeclarative5-dev qtbase5-dev-tools gcc g++ make cmake
      - run: apt install -y --no-install-recommends libmysqlclient-dev libpq5 libodbc1 libmongoc-dev libbson-dev
      - run: qmake -r "CONFIG+=release"
      - run: make
workflows:
  version: 2
  build_test1:
    jobs:
      - ubuntu-foccal
      - build_project:
          requires:
            - ubuntu-foccal
