version: 2
jobs:
  ubuntu-focal:
    docker:
      - image: buildpack-deps:focal-curl
        environment:
          DEBIAN_FRONTEND: noninteractive
    working_directory: /workspace
    steps:
      - checkout
      - run: apt-get update -qq
      - run: apt install -y --no-install-recommends qt5-default qt5-qmake libqt5sql5-mysql libqt5sql5-psql libqt5sql5-odbc libqt5sql5-sqlite libqt5core5a libqt5qml5 libqt5xml5 qtbase5-dev qtdeclarative5-dev qtbase5-dev-tools gcc g++ make cmake
      - run: apt install -y --no-install-recommends libmysqlclient-dev libpq5 libodbc1 libmongoc-dev libbson-dev
      - run: apt install -y --no-install-recommends snapd
      - run: snap install --classic cmake
      - run: wget https://github.com/treefrogframework/treefrog-framework/archive/v1.30.0.tar.gz
      - run: tar zxvf v*.*.*.tar.gz --strip-components 1
      - run: ./configure --prefix=/usr/local
      - run: make -j4 -C src
      - run: make install -C src 
      - run: make -j4 -C tools
      - run: make install -C tools
      - run: echo /usr/local/include > /etc/ld.so.conf.d/treefrog.conf
      - run: ldconfig
      - run: treefrog -v
      - persist_to_workspace:
          root: /
          paths:
            - workspace
            - usr/local
  build_project:
    docker:
      - image: buildpack-deps:focal-curl
        environment:
          DEBIAN_FRONTEND: noninteractive
    working_directory: /workspace
    steps:
      - attach_workspace:
          at: /
      - run: apt-get update -qq
      - run: apt install -y --no-install-recommends qt5-default qt5-qmake libqt5sql5-mysql libqt5sql5-psql libqt5sql5-odbc libqt5sql5-sqlite libqt5core5a libqt5qml5 libqt5xml5 qtbase5-dev qtdeclarative5-dev qtbase5-dev-tools gcc g++ make cmake
      - run: apt install -y --no-install-recommends libmysqlclient-dev libpq5 libodbc1 libmongoc-dev libbson-dev
      - run: ls -1 /usr/local/include/treefrog/
      - run: qmake -r "CONFIG+=release"
      - run: mkdir build
      - run: cd build && cmake ../
      - run: cd build && make
workflows:
  version: 2
  build_test1:
    jobs:
      - ubuntu-focal
      - build_project:
          requires:
            - ubuntu-focal
