name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
#     - name: configure
#       run: ./configure
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
    # build treefrog
    - name: dependency install
      run: sudo apt-get install -y qt5-default qt5-qmake libqt5sql5-mysql libqt5sql5-psql libqt5sql5-odbc libqt5sql5-sqlite libqt5core5a libqt5qml5 libqt5xml5 qtbase5-dev qtdeclarative5-dev qtbase5-dev-tools gcc g++ make cmake
    - name: dependency db install
      run: sudo apt-get install -y libmysqlclient-dev libpq5 libodbc1 libmongoc-dev libbson-dev
    - name: download treefrog source archive
      run: wget https://github.com/treefrogframework/treefrog-framework/archive/v1.30.0.tar.gz
    - name: expand treefrog archive 
      run: tar zxvf v*.*.*.tar.gz
    - name: configure treefrog
      run: cd treefrog-framework-*.* && ./configure
    - name: make treefrog
      run: cd treefrog-framework-*.*/src && make
    - name: make install treefrog
      run: cd treefrog-framework-*.*/src && sudo make install
    - name: make treefrog tools
      run: cd treefrog-framework-*.*/tools && make
    - name: make install treefrog tools
      run: cd treefrog-framework-*.*/tools && sudo make install
    - name: update share library dependency info
      run: sudo ldconfig

    # build project files
    - name: execute qmake.
      run: ./configure
    - name: execute qmake.
      run: qmake -r "CONFIG+=release"
    - name: execute make
      run: make
    - name: compressive archive
      run: tar cvfz app.tar.gz  config/  db/  lib/  plugin/  public/  sql/
    - name: staging
      run: mkdir staging && mv app.tar.gz staging/
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
