name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
    # build treefrog
    - name: install treefrog dependency
      run: brew install mysql-connector-c qt5
    - name: resolve path
      run: echo 'export PATH="/usr/local/opt/mysql-client/bin:$PATH"' >> /Users/runner/.bash_profile && echo export LDFLAGS="-L/usr/local/opt/mysql-client/lib"  >> /Users/runner/.bash_profile && echo export CPPFLAGS="-I/usr/local/opt/mysql-client/include"  >> /Users/runner/.bash_profile && echo export PKG_CONFIG_PATH="/usr/local/opt/mysql-client/lib/pkgconfig" >> /Users/runner/.bash_profile
    - name: install treefrog
      run: brew install treefrog

    # build project files
    - name: qmake project.
      run: qmake -r "CONFIG+=release"
    - name: make project
      run: make
    - name: compressive archive
      run: tar cvfz app.tar.gz  config/  db/  lib/  plugin/  public/  sql/
    - name: staging
      run: mkdir staging && mv app.tar.gz staging/
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
